SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[FlywayAutoPilot]'
GO
CREATE TABLE [dbo].[FlywayAutoPilot]
(
[have] [nchar] (10) NULL,
[fun] [nchar] (10) NULL,
[everyone] [nchar] (10) NULL
)
GO

