SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[LG]'
GO
CREATE TABLE [dbo].[LG]
(
[Will] [nchar] (10) NULL,
[Nic] [nchar] (10) NULL
)
GO

